DO
$do$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'ml_user') THEN

      CREATE USER ml_user WITH PASSWORD 'ml_password';
END IF;
END
$do$;

CREATE DATABASE ml_data WITH OWNER ml_user;

\c ml_data

GRANT ALL PRIVILEGES ON DATABASE ml_data TO ml_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ml_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ml_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ml_user;